name: Generate dependabot config

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *"

jobs:
  dependabot_config_generator:
    runs-on: ubuntu-latest
    name: Dependabot config generator for terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Generate config
        id: generator
        uses: ./
        with:
          labels: "terraform,dependency"
          schedule-interval: "daily"
          excluded-paths: "/example/excluded"
      - name: Create Pull Request
        if: steps.generator.outputs.file-has-changed
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          commit-message: Update dependabot config
          title: Update dependabot config
          body: Update dependabot config to reflect latest repo state
